server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-menus


# 接口文档地址，后续写入nacos
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ljw.aimenus.controller

knife4j:
  enable: true
  setting:
    language: zh_cn